"""Research Generator — spawns new research projects from correlations.

When the Correlation Engine finds high-scoring cross-topic patterns,
this module creates structured research projects that feed findings
back into Galactia — the self-improving feedback loop.

Each research project:
  1. Gets a codename and thesis
  2. Has specific research questions generated by LLM
  3. Gathers initial evidence from the knowledge store
  4. Produces findings that feed BACK into Galactia as new scored knowledge
  5. Tracks progress and completion

Usage:
    from galactia.research_gen import create_research, run_research, list_projects
"""

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from utils.llm_client import call_llm

DATA_DIR = Path(__file__).parent / "data"
PROJECTS_DIR = DATA_DIR / "research_projects"
PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
PROJECTS_INDEX = DATA_DIR / "research_index.json"


# ── Project Creation ───────────────────────────────────────────

RESEARCH_DESIGN_PROMPT = """You are the RESEARCH ARCHITECT for NCL Galactia — the functioning memory of NCC.

A correlation has been detected between knowledge clusters. Your job is to design
a focused research project that will deepen NCL's understanding.

Design a research project with:
1. CODENAME: A memorable 1-2 word codename (e.g., "DARK RESONANCE", "SIGNAL DRIFT")
2. THESIS: A clear, testable thesis statement
3. RESEARCH QUESTIONS: 3-5 specific questions to investigate
4. METHODOLOGY: How to investigate (what to look for, what evidence would confirm/deny)
5. EXPECTED IMPACT: What NCL gains from this research
6. INITIAL ASSESSMENT: Your preliminary analysis based on the correlation data

Output ONLY valid JSON:
{
    "codename": "<PROJECT CODENAME>",
    "thesis": "<testable thesis>",
    "research_questions": ["q1", "q2", "q3"],
    "methodology": "<brief methodology>",
    "expected_impact": "<what NCL learns>",
    "initial_assessment": "<2-3 paragraph preliminary analysis>",
    "priority": "<HIGH|MEDIUM|LOW>",
    "estimated_depth": "<SHALLOW|MEDIUM|DEEP>"
}
"""

RESEARCH_EXECUTE_PROMPT = """You are a RESEARCH ANALYST for NCL Galactia.

You are working on research project "{codename}".

THESIS: {thesis}

RESEARCH QUESTIONS:
{questions}

EVIDENCE FROM KNOWLEDGE STORE:
{evidence}

Conduct your analysis. For each research question:
1. Assess what the evidence supports
2. Identify what's still unknown
3. Rate your confidence in findings

Then synthesize overall findings that should be fed back into Galactia as new knowledge.

Output ONLY valid JSON:
{{
    "findings": [
        {{
            "question": "<research question>",
            "answer": "<what the evidence shows>",
            "confidence": "<HIGH|MEDIUM|LOW>",
            "evidence_strength": <0-100>,
            "unknowns": ["<what's still unknown>"]
        }}
    ],
    "synthesis": "<overall synthesis paragraph>",
    "new_claims": [
        {{
            "claim": "<new knowledge claim>",
            "confidence": "<HIGH|MEDIUM|LOW>",
            "supporting_evidence": "<brief>",
            "truth_estimate": <0-100>
        }}
    ],
    "follow_up_topics": ["<topic that needs more investigation>"],
    "thesis_status": "SUPPORTED|PARTIALLY_SUPPORTED|INCONCLUSIVE|REFUTED"
}}
"""


def create_research(correlation: dict) -> dict:
    """Create a new research project from a correlation."""
    topics = correlation.get("topics", [])
    claims = correlation.get("claims", [])
    explanation = correlation.get("explanation", "")
    direction = correlation.get("research_direction", "")

    user_msg = f"""Design a research project for this correlation:

CORRELATED TOPICS: {', '.join(topics)}
RELATED CLAIMS:
{chr(10).join(f'- {c}' for c in claims)}

WHY THIS MATTERS: {explanation}
SUGGESTED DIRECTION: {direction}
RESEARCH-WORTHY SCORE: {correlation.get('research_worthy', 0)}/100
"""

    print(f"[RESEARCH GEN] Designing project for: {' <-> '.join(topics)}")

    try:
        raw = call_llm(
            system_prompt=RESEARCH_DESIGN_PROMPT,
            user_message=user_msg,
            json_mode=True,
            temperature=0.5,
        )
        design = json.loads(raw)

        project_id = f"RP-{uuid4().hex[:8].upper()}"
        now = datetime.now(timezone.utc).isoformat()

        project = {
            "id": project_id,
            "codename": design.get("codename", "UNNAMED"),
            "status": "active",
            "created": now,
            "last_updated": now,
            "correlation_source": correlation,
            "topics": topics,
            "thesis": design.get("thesis", ""),
            "research_questions": design.get("research_questions", []),
            "methodology": design.get("methodology", ""),
            "expected_impact": design.get("expected_impact", ""),
            "initial_assessment": design.get("initial_assessment", ""),
            "priority": design.get("priority", "MEDIUM"),
            "estimated_depth": design.get("estimated_depth", "MEDIUM"),
            "findings": [],
            "new_knowledge": [],
            "cycles_run": 0,
        }

        # Save project
        project_file = PROJECTS_DIR / f"{project_id}.json"
        project_file.write_text(json.dumps(project, indent=2), encoding="utf-8")

        # Update index
        _update_index(project)

        print(f"[RESEARCH GEN] Created: {project_id} — \"{design.get('codename', 'UNNAMED')}\"")
        print(f"  Thesis: {design.get('thesis', '')[:100]}")
        return project

    except Exception as e:
        print(f"[RESEARCH GEN] Failed to create project: {e}")
        return {}


def run_research(project_id: str) -> dict:
    """Execute a research cycle on an existing project."""
    project_file = PROJECTS_DIR / f"{project_id}.json"
    if not project_file.exists():
        print(f"[RESEARCH] Project {project_id} not found")
        return {}

    project = json.loads(project_file.read_text(encoding="utf-8"))
    codename = project["codename"]

    print(f"[RESEARCH] Running cycle for \"{codename}\" ({project_id})")

    # Gather evidence from knowledge store
    from galactia.knowledge_store import get_topic_detail, get_knowledge_graph

    evidence_parts = []
    for topic in project["topics"]:
        detail = get_topic_detail(topic)
        if detail:
            evidence_parts.append(f"TOPIC: {detail['name']} (avg score: {detail['avg_score']}, {detail['count']} posts)")
            for claim in detail.get("top_claims", [])[:5]:
                evidence_parts.append(f"  - {claim}")

    evidence = "\n".join(evidence_parts) if evidence_parts else "Limited evidence available."

    questions = "\n".join(f"{i+1}. {q}" for i, q in enumerate(project["research_questions"]))

    user_msg = RESEARCH_EXECUTE_PROMPT.format(
        codename=codename,
        thesis=project["thesis"],
        questions=questions,
        evidence=evidence,
    )

    try:
        raw = call_llm(
            system_prompt="You are a rigorous research analyst. Output only valid JSON.",
            user_message=user_msg,
            json_mode=True,
            temperature=0.4,
        )
        result = json.loads(raw)

        # Update project with findings
        project["findings"].append({
            "cycle": project["cycles_run"] + 1,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "result": result,
        })
        project["cycles_run"] += 1
        project["last_updated"] = datetime.now(timezone.utc).isoformat()

        # Extract new knowledge to feed back into Galactia
        new_claims = result.get("new_claims", [])
        project["new_knowledge"].extend(new_claims)

        # Check if thesis is resolved
        thesis_status = result.get("thesis_status", "INCONCLUSIVE")
        if thesis_status in ("SUPPORTED", "REFUTED"):
            project["status"] = "completed"
            project["conclusion"] = thesis_status

        project_file.write_text(json.dumps(project, indent=2), encoding="utf-8")
        _update_index(project)

        print(f"[RESEARCH] Cycle complete. Thesis: {thesis_status}")
        print(f"  New claims: {len(new_claims)}")
        if result.get("synthesis"):
            print(f"  Synthesis: {result['synthesis'][:120]}...")

        return result

    except Exception as e:
        print(f"[RESEARCH] Cycle failed: {e}")
        return {}


def feed_back_to_galactia(project_id: str) -> int:
    """Feed research findings back into Galactia as new scored knowledge.

    This is THE FEEDBACK LOOP — research produces new claims which enter
    the knowledge store and can trigger NEW correlations and NEW research.
    """
    project_file = PROJECTS_DIR / f"{project_id}.json"
    if not project_file.exists():
        return 0

    project = json.loads(project_file.read_text(encoding="utf-8"))
    new_knowledge = project.get("new_knowledge", [])

    if not new_knowledge:
        return 0

    from galactia.knowledge_store import store_scored

    # Convert research claims into scored posts
    feedback_posts = []
    for claim in new_knowledge:
        feedback_posts.append({
            "id": f"research_{project_id}_{uuid4().hex[:6]}",
            "text": claim.get("claim", ""),
            "clean_text": claim.get("claim", ""),
            "author": f"GALACTIA_RESEARCH/{project['codename']}",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "source": "research_feedback",
            "truth_score": claim.get("truth_estimate", 50),
            "credibility_score": 80,  # Research-generated = high credibility
            "accountability_score": 90,  # Full traceability
            "overall_score": round(
                claim.get("truth_estimate", 50) * 0.5 + 80 * 0.3 + 90 * 0.2
            ),
            "topics": project.get("topics", []),
            "key_claims": [claim.get("claim", "")],
            "context": f"Research project {project['codename']}: {claim.get('supporting_evidence', '')}",
            "research_spawned": project_id,
        })

    store_scored(feedback_posts)

    # Mark claims as fed back
    project["new_knowledge"] = []  # Clear after feeding back
    project["feedback_count"] = project.get("feedback_count", 0) + len(feedback_posts)
    project_file.write_text(json.dumps(project, indent=2), encoding="utf-8")

    print(f"[FEEDBACK] Fed {len(feedback_posts)} research claims back into Galactia")
    return len(feedback_posts)


# ── Index Management ───────────────────────────────────────────

def _update_index(project: dict):
    """Update the research projects index."""
    index = _load_index()
    index["projects"][project["id"]] = {
        "codename": project["codename"],
        "status": project["status"],
        "topics": project["topics"],
        "priority": project.get("priority", "MEDIUM"),
        "created": project["created"],
        "cycles_run": project.get("cycles_run", 0),
    }
    index["last_updated"] = datetime.now(timezone.utc).isoformat()
    PROJECTS_INDEX.write_text(json.dumps(index, indent=2), encoding="utf-8")


def _load_index() -> dict:
    if PROJECTS_INDEX.exists():
        return json.loads(PROJECTS_INDEX.read_text(encoding="utf-8"))
    return {"projects": {}, "last_updated": None}


# ── Queries ────────────────────────────────────────────────────

def list_projects(status: str | None = None) -> list[dict]:
    """List all research projects, optionally filtered by status."""
    index = _load_index()
    projects = list(index.get("projects", {}).values())
    if status:
        projects = [p for p in projects if p.get("status") == status]
    return projects


def get_project(project_id: str) -> dict | None:
    """Get full project details."""
    project_file = PROJECTS_DIR / f"{project_id}.json"
    if project_file.exists():
        return json.loads(project_file.read_text(encoding="utf-8"))
    return None


def get_active_projects() -> list[dict]:
    """Get all active research projects."""
    return list_projects(status="active")


def research_stats() -> dict:
    """Get research system statistics."""
    index = _load_index()
    projects = index.get("projects", {})

    active = sum(1 for p in projects.values() if p.get("status") == "active")
    completed = sum(1 for p in projects.values() if p.get("status") == "completed")
    total_cycles = sum(p.get("cycles_run", 0) for p in projects.values())

    return {
        "total_projects": len(projects),
        "active": active,
        "completed": completed,
        "total_research_cycles": total_cycles,
    }


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Galactia Research Generator")
    parser.add_argument("--list", action="store_true", help="List all projects")
    parser.add_argument("--stats", action="store_true", help="Show research stats")
    parser.add_argument("--run", type=str, help="Run research cycle on project ID")
    parser.add_argument("--feedback", type=str, help="Feed project findings back to Galactia")
    args = parser.parse_args()

    if args.list:
        for p in list_projects():
            print(f"  [{p['status']}] {p.get('codename', '?')} — {', '.join(p.get('topics', []))}")
    elif args.stats:
        for k, v in research_stats().items():
            print(f"  {k}: {v}")
    elif args.run:
        run_research(args.run)
    elif args.feedback:
        feed_back_to_galactia(args.feedback)
    else:
        parser.print_help()
