#!/bin/bash
# Deployment script for test
# Generated by REPO DEPOT FLYWHEEL

echo "Deploying test..."

# Install dependencies
pip install -r requirements.txt

# Run tests
python -m pytest tests/ -v

# Start application
python app.py
